<?php

echo "<!DOCTYPE HTML>\n";
echo "<html>\n";
echo "	<head>\n";
echo "		<title>Adam Mertzenich</title>\n";
echo "		<meta charset=\"utf-8\" />\n";
echo "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n";
echo "		<!--[if lte IE 8]><script src=\"assets/js/ie/html5shiv.js\"></script><![endif]-->\n";
echo "		<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n";
echo "		<noscript><link rel=\"stylesheet\" href=\"assets/css/noscript.css\" /></noscript>\n";
echo "		<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"assets/css/ie8.css\" /><![endif]-->\n";
echo "	</head>\n";
echo "	<body>\n";
echo "\n";
echo "		<!-- Wrapper-->\n";
echo "			<div id=\"wrapper\">\n";
echo "\n";
echo "				<!-- Nav -->\n";
echo "					<nav id=\"nav\">\n";
echo "						<a href=\"#me\" class=\"icon fa-home active\"><span>Home</span></a>\n";
echo "						<a href=\"#work\" class=\"icon fa-folder\"><span>Work</span></a>\n";
echo "						<a href=\"#contact\" class=\"icon fa-envelope\"><span>Contact</span></a>\n";
echo "						<a href=\"http://adammertzenich.github.io\" class=\"icon fa-github\"><span>Github</span></a>\n";
echo "					</nav>\n";
echo "\n";
echo "				<!-- Main -->\n";
echo "					<div id=\"main\">\n";
echo "\n";
echo "						<!-- Me -->\n";
echo "							<article id=\"me\" class=\"panel\">\n";
echo "								<header>\n";
echo "									<h1>Adam Mertzenich</h1>\n";
echo "									<p><!--[-->Python, Java, and Web Developer<!--]--></p>\n";
echo "								</header>\n";
echo "								<a href=\"#work\" class=\"jumplink pic\">\n";
echo "									<span class=\"arrow icon fa-chevron-right\"><span>My Work</span></span>\n";
echo "									<img src=\"images/me.jpg\" alt=\"\" />\n";
echo "								</a>\n";
echo "							</article>\n";
echo "\n";
echo "						<!-- Work -->\n";
echo "							<article id=\"work\" class=\"panel\">\n";
echo "								<header>\n";
echo "									<h2>Work</h2>\n";
echo "								</header>\n";
echo "								<p>\n";
echo "									Here you can find the projects that I have worked on in the past. I will mainly focus on\n";
echo "									python and web development but as I learn more java there may be some of that as well.\n";
echo "								</p>\n";
echo "								<section>\n";
echo "									<div class=\"row\">\n";
echo "										<div class=\"4u 12u$(mobile)\">\n";
echo "											<p> Python Calculator GUI </p>\n";
echo "											<a href=\"https://github.com/adammertzenich/PyCalcGUI\" class=\"image fit\"><img src=\"images/pic01.png\" alt=\"\"></a>\n";
echo "										</div>\n";
echo "									</div>\n";
echo "								</section>\n";
echo "							</article>\n";
echo "\n";
echo "						<!-- Contact -->\n";
echo "							<article id=\"contact\" class=\"panel\">\n";
echo "								<header>\n";
echo "									<h2>Contact Me</h2>\n";
echo "								</header>\n";
echo "								<form action=\"#\" method=\"post\">\n";
echo "									<div>\n";
echo "										<div class=\"row\">\n";
echo "											<div class=\"6u 12u$(mobile)\">\n";
echo "												<input type=\"text\" name=\"name\" placeholder=\"Name\" />\n";
echo "											</div>\n";
echo "											<div class=\"6u$ 12u$(mobile)\">\n";
echo "												<input type=\"text\" name=\"email\" placeholder=\"Email\" />\n";
echo "											</div>\n";
echo "											<div class=\"12u$\">\n";
echo "												<input type=\"text\" name=\"subject\" placeholder=\"Subject\" />\n";
echo "											</div>\n";
echo "											<div class=\"12u$\">\n";
echo "												<textarea name=\"message\" placeholder=\"Message\" rows=\"8\">
